AUTOENCODER_PRESETS = {
    "default_ani": {
        "latent_dim": 16,
        "num_bessel": 8,
        "num_polynomial_cutoff": 5,
        "max_ell": 3,
        "num_interactions": 2,
        "hidden_irreps": "192x0e + 192x1o + 192x2e",
        "mlp_irreps": "16x0e",
        "correlation": 3,
        "gate": "silu",
        "interaction": "RealAgnosticResidualInteractionBlock",
        "interaction_first": "RealAgnosticInteractionBlock",
        "radial_mlp": [64, 64, 64],
        "radial_type": "bessel",
        "distance_transform": "None",
        "pair_repulsion": False,
    },
    "default_cli": {
        "latent_dim": 16,
        "num_bessel": 8,
        "num_polynomial_cutoff": 5,
        "max_ell": 3,
        "num_interactions": 2,
        "hidden_irreps": "128x0e + 128x1o",
        "mlp_irreps": "16x0e",
        "correlation": 3,
        "gate": "silu",
        "interaction": "RealAgnosticResidualInteractionBlock",
        "interaction_first": "RealAgnosticResidualInteractionBlock",
        "radial_mlp": [64, 64, 64],
        "radial_type": "bessel",
        "distance_transform": "None",
        "pair_repulsion": False,
    },
    "lightweight": {
        "latent_dim": 16,
        "num_bessel": 4,
        "num_polynomial_cutoff": 3,
        "max_ell": 2,
        "num_interactions": 1,
        "hidden_irreps": "4x0e + 4x1o",
        "mlp_irreps": "16x0e",
        "correlation": 1,
        "gate": "silu",
        "interaction": "RealAgnosticResidualInteractionBlock",
        "interaction_first": "RealAgnosticResidualInteractionBlock",
        "radial_mlp": [32, 32],
        "radial_type": "bessel",
        "distance_transform": "None",
        "pair_repulsion": False,
    },
}
